#!/usr/bin/env bash
#
# HQ-608 guard.
#
# A .gitignore pattern that contains no slash matches at EVERY directory depth.
# On 2024-08-15 the bare patterns `*.cc`, `*.h`, `*.inc` and `*.m` were added to
# this repo's .gitignore. They stripped 4,099 header files and most of the C /
# C++ / Objective-C sources out of the committed Pods/ tree, and the repo could
# not be built from a clean clone for the next two years. Nobody noticed, because
# everyone working on it already had Pods/ on disk.
#
# This script fails the build if that class of mistake is reintroduced.
#
set -euo pipefail

cd "$(dirname "$0")/.."

fail=0

note() { printf '  %s\n' "$*"; }
bad()  { fail=1; printf '\nFAIL: %s\n' "$*"; }

# ---------------------------------------------------------------------------
# 1. No unanchored ignore pattern may target a source or project-file extension.
# ---------------------------------------------------------------------------
# Build artifacts (*.ipa, *.dSYM, *.hmap) are fine unanchored. Source is not.
source_ext_re='\.(c|cc|cpp|cxx|c\+\+|h|hh|hpp|hxx|ipp|inc|m|mm|s|swift|java|kt|rb|py|js|ts|tsx|xcodeproj|xcworkspace|pbxproj|xcscheme|podspec|storyboard|xib|xcassets|plist|lock)$'

while IFS= read -r raw; do
  line="${raw%$'\r'}"
  # strip comments and blanks
  [[ "$line" =~ ^[[:space:]]*# ]] && continue
  [[ -z "${line// }" ]] && continue
  pattern="$line"
  # a negation is a re-include; it can only widen what is committed
  [[ "$pattern" == !* ]] && continue
  # a pattern containing a slash (other than a bare trailing one) is anchored
  stripped="${pattern%/}"
  [[ "$stripped" == */* ]] && continue
  # only globs are in scope. A literal unanchored filename (playground.xcworkspace)
  # targets one known file; a glob sweeps a whole tree, which is the HQ-608 failure.
  [[ "$stripped" != *[*?[]* ]] && continue
  if [[ "$stripped" =~ $source_ext_re ]]; then
    bad "unanchored ignore pattern '$pattern' in .gitignore"
    note "It matches at every directory depth, including inside Pods/."
    note "Anchor it to the directory it belongs to, e.g. '/BBNDaily/Generated/${stripped}'."
  fi
done < .gitignore

# ---------------------------------------------------------------------------
# 2. No tracked file may also be matched by .gitignore.
# ---------------------------------------------------------------------------
# This is the general form of the same failure: an ignore rule that quietly
# covers something the build needs.
shadowed="$(git ls-files --cached --ignored --exclude-standard || true)"
if [[ -n "$shadowed" ]]; then
  bad "tracked files are also matched by .gitignore:"
  printf '%s\n' "$shadowed" | head -20 | sed 's/^/    /'
fi

# ---------------------------------------------------------------------------
# 3. The dependency contract: Podfile.lock tracked, Pods/ not tracked.
# ---------------------------------------------------------------------------
if [[ -z "$(git ls-files Podfile.lock)" ]]; then
  bad "Podfile.lock is not tracked. It is the only thing pinning pod versions."
fi

pods_tracked="$(git ls-files Pods | wc -l | tr -d ' ')"
if [[ "$pods_tracked" != "0" ]]; then
  bad "$pods_tracked file(s) under Pods/ are tracked."
  note "Pods/ is not vendored in this repo; it is regenerated by 'pod install'."
  note "A partially-tracked Pods/ tree is exactly the HQ-608 bug."
fi

if [[ "$fail" -eq 0 ]]; then
  echo "gitignore scope check: OK"
fi
exit "$fail"
